# This file is used by Tahoe to make a lightweight startup for `$ make tahoe.up`
# For the full version, use `$ make tahoe.up.full`

version: "2.1"

services:
  chrome:
    image: hello-world
    command: /hello
  elasticsearch:
    image: hello-world
    command: /hello
  firefox:
    image: hello-world
    command: /hello
  credentials:
    image: hello-world
    command: /hello
  discovery:
    image: hello-world
    command: /hello
  ecommerce:
    image: hello-world
    command: /hello
  edx_notes_api:
    image: hello-world
    command: /hello
  forum:
    image: hello-world
    command: /hello
