version: "2.1"

services:
  lms:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - edxapp_media:/edx/var/edxapp/media
      - edxapp_uploads:/edx/var/edxapp/uploads
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
      - ${DEVSTACK_WORKSPACE}/customer_themes:/edx/var/edxapp/themes/customer_themes:cached
      - ${DEVSTACK_WORKSPACE}/edx-theme-codebase:/edx/var/edxapp/themes/edx-theme-codebase:cached
  studio:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - edxapp_media:/edx/var/edxapp/media
      - edxapp_uploads:/edx/var/edxapp/uploads
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
      - ${DEVSTACK_WORKSPACE}/customer_themes:/edx/var/edxapp/themes/customer_themes:cached
      - ${DEVSTACK_WORKSPACE}/edx-theme-codebase:/edx/var/edxapp/themes/edx-theme-codebase:cached
  amc:
    volumes:
      - ${DEVSTACK_WORKSPACE}/amc:/opt/amc:cached

volumes:
  credentials_node_modules:
  discovery_node_modules:
  ecommerce_node_modules:
  edxapp_node_modules:
  edxapp_media:
  edxapp_uploads:
